dynamicPlugins:
  rootDirectory: dynamic-plugins-root
  frontend:
    red-hat-developer-hub.backstage-plugin-global-floating-action-button:
      mountPoints:
        - mountPoint: application/listener
          importName: DynamicGlobalFloatingActionButton
        - mountPoint: global.floatingactionbutton/config
          importName: NullComponent
          config:
            icon: github
            label: "Git"
            showLabel: true
            toolTip: "Github"
            to: https://github.com/redhat-developer/rhdh
    red-hat-developer-hub.backstage-plugin-bulk-import:
      mountPoints:
        - mountPoint: global.floatingactionbutton/config
          importName: BulkImportPage
          config:
            slot: "bottom-left"
            icon: bulkImportIcon
            label: "Bulk import"
            toolTip: "Register multiple repositories in bulk"
            to: /bulk-import
            excludeOnPaths: ["/catalog"]
      appIcons:
        - name: bulkImportIcon
          importName: BulkImportIcon
      dynamicRoutes:
        - path: /bulk-import
          importName: BulkImportPage
          menuItem:
            icon: bulkImportIcon
            text: Bulk import
