kind: Backstage
apiVersion: rhdh.redhat.com/v1alpha5
metadata:
  name: rhdh-rbac
spec:
  deployment:
    patch:
      spec:
        replicas: 1
        template:
          spec:
            imagePullSecrets:
              - name: "rh-pull-secret"
            containers:
              - name: backstage-backend
                image: "quay.io/$QUAY_REPO:$TAG_NAME"
            initContainers:
              - name: install-dynamic-plugins
                image: "quay.io/$QUAY_REPO:$TAG_NAME"
                # Increase ephemeral storage limit for dynamic plugins installation
                # This prevents "No space left on device" errors during plugin extraction
                resources:
                  requests:
                    cpu: 250m
                    memory: 256Mi
                  limits:
                    cpu: 1000m
                    memory: 2.5Gi
                    ephemeral-storage: 10Gi
  application:
    route:
      enabled: false
    appConfig:
      configMaps:
        - name: app-config-rhdh
      mountPath: /opt/app-root/src
    dynamicPluginsConfigMapName: dynamic-plugins
    extraEnvs:
      envs:
        - name: SEGMENT_TEST_MODE
          value: "true"
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: NODE_ENV
          value: "production"
      secrets:
        - name: rhdh-secrets
    extraFiles:
      configMaps:
        - name: rbac-policy
      mountPath: /opt/app-root/src/rbac
