kind: Backstage
apiVersion: rhdh.redhat.com/v1alpha5
metadata:
  name: rhdh
spec:
  deployment:
    patch:
      spec:
        replicas: 1
        template:
          spec:
            imagePullSecrets:
              - name: "rh-pull-secret"
            containers:
              - name: backstage-backend
                image: "quay.io/$QUAY_REPO:$TAG_NAME"
            initContainers:
              - name: install-dynamic-plugins
                image: "quay.io/$QUAY_REPO:$TAG_NAME"
                # Increase ephemeral storage limit for dynamic plugins installation
                # This prevents "No space left on device" errors during plugin extraction
                resources:
                  requests:
                    cpu: 250m
                    memory: 256Mi
                  limits:
                    cpu: 1000m
                    memory: 2.5Gi
                    ephemeral-storage: 10Gi
  application:
    route:
      enabled: false
    appConfig:
      configMaps:
        - name: app-config-rhdh
        - name: dynamic-plugins-config
        - name: dynamic-global-floating-action-button-config
        - name: dynamic-global-header-config
      mountPath: /opt/app-root/src
    dynamicPluginsConfigMapName: dynamic-plugins
    extraEnvs:
      envs:
        - name: NODE_OPTIONS
          value: "--no-node-snapshot"
        - name: NODE_ENV
          value: "production"
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
      secrets:
        - name: rhdh-secrets
        - name: redis-secret
