kind: Backstage
apiVersion: rhdh.redhat.com/v1alpha5
metadata:
  name: rhdh-rbac
spec:
  deployment:
    patch:
      spec:
        replicas: 1
        template:
          spec:
            imagePullSecrets:
              - name: "rh-pull-secret"
            containers:
              - name: backstage-backend
                image: "quay.io/$QUAY_REPO:$TAG_NAME"
            initContainers:
              - name: install-dynamic-plugins
                image: "quay.io/$QUAY_REPO:$TAG_NAME"
            volumes:
              - name: dynamic-plugins-root
                ephemeral:
                  volumeClaimTemplate:
                    spec:
                      accessModes:
                        - ReadWriteOnce
                      resources:
                        requests:
                          storage: 5Gi
  application:
    route:
      enabled: false
    appConfig:
      configMaps:
        - name: app-config-rhdh
      mountPath: /opt/app-root/src
    dynamicPluginsConfigMapName: dynamic-plugins
    extraEnvs:
      envs:
        - name: SEGMENT_TEST_MODE
          value: "true"
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: "0"
        - name: NODE_ENV
          value: "production"
        - name: CATALOG_INDEX_IMAGE
          value: "quay.io/rhdh/plugin-catalog-index:1.9"
          containers:
            - install-dynamic-plugins
      secrets:
        - name: rhdh-secrets
    extraFiles:
      configMaps:
        - name: rbac-policy
      mountPath: /opt/app-root/src/rbac
