#!/bin/bash
#
# Populates dynamic-plugins-root with EVERY OCI plugin from the catalog index,
# for the cluster-free plugin sanity check (playwright.plugin-sanity.config.ts).
#
# The index ships most plugins disabled by default (products opt in via their
# own config), so a plain `includes` config would install nothing; this script
# generates a config re-enabling every declared package and delegates the
# install to populate.sh.
#
# Requires skopeo and jq. Usage:
#   CATALOG_INDEX_IMAGE=quay.io/rhdh/plugin-catalog-index:next \
#     ./e2e-tests/local-harness/populate-catalog-index.sh
set -e

: "${CATALOG_INDEX_IMAGE:?CATALOG_INDEX_IMAGE must be set (e.g. quay.io/rhdh/plugin-catalog-index:next)}"

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

workdir="$(mktemp -d)"
trap 'rm -rf "$workdir"' EXIT

refs="$("$DIR/catalog-index-refs.sh" "$CATALOG_INDEX_IMAGE")"
excluded_refs="$("$DIR/catalog-index-refs.sh" "$CATALOG_INDEX_IMAGE" --excluded)"

if [[ -z "$refs" ]]; then
  echo "No packages left to install from ${CATALOG_INDEX_IMAGE}" >&2
  if [[ -n "$excluded_refs" ]]; then
    echo "every declared package matched $DIR/plugin-sanity-excludes.txt" >&2
  fi
  exit 1
fi

# Counted once and reused below. `grep -c` exits 1 when it counts zero, and a
# bare assignment IS enough to trip set -e (unlike the same substitution inside
# an echo argument), hence the `|| true`.
oci_count="$(grep -c '^oci://' <<< "$refs" || true)"
if [[ "$oci_count" -eq 0 ]]; then
  # Without this the run continues, installs nothing, writes
  # expected_oci_packages=0, and only fails later when the spec rejects the
  # breadcrumb - pointing at the breadcrumb instead of at the cause.
  echo "No oci:// packages left to install from ${CATALOG_INDEX_IMAGE}" >&2
  echo "no installable refs found; check $DIR/plugin-sanity-excludes.txt" >&2
  exit 1
fi

{
  echo "# Generated by populate-catalog-index.sh for ${CATALOG_INDEX_IMAGE}"
  echo "includes:"
  echo "  - dynamic-plugins.default.yaml"
  echo "plugins:"
  while read -r ref; do
    echo "  - package: \"$ref\""
    echo "    enabled: true"
  done <<< "$refs"
  # Excluded packages must be disabled EXPLICITLY. The `includes` above pulls in
  # the index's own list, so simply leaving one out installs it anyway.
  if [[ -n "$excluded_refs" ]]; then
    while read -r ref; do
      echo "  - package: \"$ref\""
      echo "    enabled: false"
    done <<< "$excluded_refs"
  fi
} > "$workdir/dynamic-plugins.catalog-index.yaml"

echo "Enabling ${oci_count} OCI package(s) from ${CATALOG_INDEX_IMAGE}"

"$DIR/populate.sh" "$workdir/dynamic-plugins.catalog-index.yaml"

# Record what this run was SUPPOSED to install, so the spec can assert it got
# the full index set. Without it the spec only checks "installed ⊆ loaded",
# which stays green when a registry hiccup, an over-broad exclude pattern or a
# stale populate left a handful of plugins behind - the exact silent underrun
# this check exists to catch.
REPO_ROOT="$(cd "$DIR/../.." && pwd)"
{
  echo "# Generated by populate-catalog-index.sh - do not edit."
  echo "image=${CATALOG_INDEX_IMAGE}"
  echo "expected_oci_packages=${oci_count}"
} > "$REPO_ROOT/dynamic-plugins-root/.catalog-index-refs"
